const addToCartButtons = document.querySelectorAll("#btn"); //allows one to select all buttons with the common id
const orderBtn = document.getElementById("orderBtn");
const message = document.getElementById("preOrderMessage");
let currentOrder = document.getElementById('order');
let cakeImage = document.getElementById("preOrderImage");
let cart = []; //initializing the cart items to empty array

function addToCart(item) {
    // Find the item in the cart
    const existingItem = cart.find(cartItem => cartItem.name === item.name);

    if (existingItem) {
        // If the item already exists, increase the quantity and update the total price
        existingItem.quantity++;
        existingItem.totalPrice = (existingItem.quantity * existingItem.price).toFixed(2);
    } else {
        // If the item doesn't exist, add it to the cart with quantity 1 and set total price
        cart.push({...item, quantity: 1, totalPrice: item.price.toFixed(2) });

    }

    updateCartDisplay(); // Update the cart display
}


// Function to display the items that are ordered
function updateCartDisplay() {
    if (cart.length === 0) { // Check if the cart is empty
        message.style.display = "block"; // Show the message
        cakeImage.style.display = "block";
        currentOrder.innerHTML = ""; // Display is empty when there are no items in the cart

    } else {
        message.style.display = "none"; // Remove the pre-order message
        cakeImage.style.display = "none";
        // Map function to iterate over each item in the cart array
        currentOrder.innerHTML = cart.map(item => `
        <div class="cart-item">
           <p> ${item.name} - ${item.quantity} x @$${item.price.toFixed(2)} $${item.totalPrice}</p>    
        </div>
  
    ` // The part in quotes is the HTML structure of each item in the array
        ).join(""); // It joins the strings generated by the map function into a single string
    }
}



// Function to make changes when add cart is clicked
addToCartButtons.forEach(button => { //using forEach because this function applies to all target buttons
    button.addEventListener('click', (event) => { //event listener for a click
        const itemElement = event.target.closest('.item'); //find the closest element with class item(its the parent container that houses the  add to cart buttons and also other information about the dessert being orderred)
        const itemName = itemElement.querySelector("#dessertName").innerText; //get the name of the dessert in the same container as the button
        const itemPrice = parseFloat(itemElement.querySelector("#price").innerText.replace('$', '')); //get price of the item and also remove dollar sign since I've used parsefloat for easier calculation
        addToCart({ name: itemName, price: itemPrice }); //add the element to the cart
    });
});

function showOrderConfirmation() {
    if (cart.length !== 0) {
        alert("Your order has been received!");
    } else {
        alert("please order your items!");
    }

}
orderBtn.addEventListener("click", showOrderConfirmation);